name: Test Build

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      
      - name: Cargo build
        id: build
        run: |
          # show supported targets
          rustup show

          # set environment variable used in this step
          origin_name=$(cargo metadata --format-version 1 | jq -j .packages[0].name)
          origin_app="$origin_name"
          target="aarch64-apple-darwin"
          target_app_suffix="-macos-arm64"
          target_dir="./target/$target/release"
          target_app="$origin_name$target_app_suffix"
      
          # build the project
          rustup target add $target
          cargo build --release --verbose --target $target

          ls -lhR $target_dir # for debug

          # rename the file to the name of the project         
          mv "$target_dir/$origin_app" "$target_dir/$target_app"
          
          # set variable to GITHUB_OUTPUT
          echo "target_dir=$target_dir" >> $GITHUB_OUTPUT
          echo "target_app=$target_app" >> $GITHUB_OUTPUT
          echo "version=v$(cargo metadata --format-version 1 | jq -j .packages[0].version)" >> $GITHUB_OUTPUT
